/* Garrett Chan */
INSERT INTO songs VALUES(1,'Overture');
INSERT INTO songs VALUES(2,'A Bar In Amsterdam');
INSERT INTO songs VALUES(3,'Demon Kitty Rag');
INSERT INTO songs VALUES(4,'Tea With Cinnamon');
INSERT INTO songs VALUES(5,'Hey Ho on the Devil''s Back');
INSERT INTO songs VALUES(6,'Wading in Deeper');
INSERT INTO songs VALUES(7,'Le Pop');
INSERT INTO songs VALUES(8,'Der Kapitan');
INSERT INTO songs VALUES(9,'Virginia Clemm');
INSERT INTO songs VALUES(10,'Play My Darling,  Play');
INSERT INTO songs VALUES(11,'To the Sea');
INSERT INTO songs VALUES(12,'Mother Superior');
INSERT INTO songs VALUES(13,"Ain't no Thang");
INSERT INTO songs VALUES(14,'A Kiss Before You Go');
INSERT INTO songs VALUES(15,'I Will Dance (When I Walk Away)');
INSERT INTO songs VALUES(16,'Cherry Pie');
INSERT INTO songs VALUES(17,'Land of Confusion');
INSERT INTO songs VALUES(18,'Lady Marlene');
INSERT INTO songs VALUES(19,'Rock-Paper-Scissors');
INSERT INTO songs VALUES(20,'Cocktails and Ruby Slippers');
INSERT INTO songs VALUES(21,'Soviet Trumpeter');
INSERT INTO songs VALUES(22,'Loathsome M');
INSERT INTO songs VALUES(23,"Shepherd's Song");
INSERT INTO songs VALUES(24,'Gypsy Flee');
INSERT INTO songs VALUES(25,"God's Great Dust Storm");
INSERT INTO songs VALUES(26,'Ouch');
INSERT INTO songs VALUES(27,'Listening to the World');
INSERT INTO songs VALUES(28,'Johnny Blowtorch');
INSERT INTO songs VALUES(29,'Flash');
INSERT INTO songs VALUES(30,'Driving After You');
INSERT INTO songs VALUES(31,'My Own Tune');
INSERT INTO songs VALUES(32,'Badlands');
INSERT INTO songs VALUES(33,'Old De Spain');
INSERT INTO songs VALUES(34,'Oh My God');
INSERT INTO songs VALUES(35,'Lady Gray');
INSERT INTO songs VALUES(36,'Shine Like Neon Rays');
INSERT INTO songs VALUES(37,'Flash in the Dark');
INSERT INTO songs VALUES(38,'My Dear');
INSERT INTO songs VALUES(39,'Bad Girl');
INSERT INTO songs VALUES(40,'Rockland');
INSERT INTO songs VALUES(41,'Curvaceous Needs');
INSERT INTO songs VALUES(42,'Borka');
INSERT INTO songs VALUES(43,'Let it Snow');
