/* Garrett Chan */
INSERT INTO airports VALUES('Aberdeen ','APG','Phillips AAF ','United States ','US ');
INSERT INTO airports VALUES('Aberdeen ','ABR','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Abilene ','DYS','Dyess AFB ','United States ','US ');
INSERT INTO airports VALUES('Abilene ','ABI','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Abingdon ','VJI','Virginia Highlands ','United States ','US ');
INSERT INTO airports VALUES('Ada ','ADT','Ada ','United States ','US ');
INSERT INTO airports VALUES('Adak Island ','ADK','Adak Island Ns ','United States ','US ');
INSERT INTO airports VALUES('Adrian ','ADG','Lenawee County ','United States ','US ');
INSERT INTO airports VALUES('Afton ','AFO','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Aiken ','AIK','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Ainsworth ','ANW','Ainsworth ','United States ','US ');
INSERT INTO airports VALUES('Akhiok ','AKK','Akhiok SPB ','United States ','US ');
INSERT INTO airports VALUES('Akiachak ','KKI','Spb ','United States ','US ');
INSERT INTO airports VALUES('Akiak ','AKI','Akiak ','United States ','US ');
INSERT INTO airports VALUES('Akron CO ' ,'AKO','Colorado Plains Regional Airport ','United States ','US ');
INSERT INTO airports VALUES('Akron/Canton OH ' ,'CAK','Akron/canton Regional ','United States ','US ');
INSERT INTO airports VALUES('Akron/Canton ','AKC','Fulton International ','United States ','US ');
INSERT INTO airports VALUES('Akutan ','KQA','Akutan ','United States ','US ');
INSERT INTO airports VALUES('Alakanuk ','AUK','Alakanuk ','United States ','US ');
INSERT INTO airports VALUES('Alameda ','NGZ','NAS ','United States ','US ');
INSERT INTO airports VALUES('Alamogordo ','HMN','Holloman AFB ','United States ','US ');
INSERT INTO airports VALUES('Alamogordo ','ALM','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Alamosa ','ALS','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Albany ','NAB','Albany NAS ','United States ','US ');
INSERT INTO airports VALUES('Albany ','ABY','Dougherty County ','United States ','US ');
INSERT INTO airports VALUES('Albany ','ALB','Albany International ','United States ','US ');
INSERT INTO airports VALUES('Albany ','CVO','Albany ','United States ','US ');
INSERT INTO airports VALUES('Albert Lea ','AEL','Albert Lea ','United States ','US ');
INSERT INTO airports VALUES('Albuquerque ','ABQ','Albuquerque International ','United States ','US ');
INSERT INTO airports VALUES('Aleknagik ','WKK','Aleknagik ','United States ','US ');
INSERT INTO airports VALUES('Aleneva ','AED','Aleneva ','United States ','US ');
INSERT INTO airports VALUES( 'Alexander City AL ' ,'ALX','Thomas C Russell Fld ','United States ','US ');
INSERT INTO airports VALUES( 'Alexandria LA ' ,'AEX','Alexandria International ','United States ','US ');
INSERT INTO airports VALUES('Alexandria ','ESF','Esler Field ','United States ','US ');
INSERT INTO airports VALUES('Alexandria ','AXN','Alexandria ','United States ','US ');
INSERT INTO airports VALUES('Alexandria Bay ','AXB','Alexandria Bay ','United States ','US ');
INSERT INTO airports VALUES('Algona ','AXG','Algona ','United States ','US ');
INSERT INTO airports VALUES('Alice ','ALI','International ','United States ','US ');
INSERT INTO airports VALUES( 'Aliceville AL ' ,'AIV','George Downer ','United States ','US ');
INSERT INTO airports VALUES('Alitak ','ALZ','Alitak SPB ','United States ','US ');
INSERT INTO airports VALUES('Allakaket ','AET','Allakaket ','United States ','US ');
INSERT INTO airports VALUES('Alliance ','AIA','Alliance ','United States ','US ');
INSERT INTO airports VALUES('Alma ','AMN','Gratiot Community ','United States ','US ');
INSERT INTO airports VALUES('Alpena ','APN','Alpena County Regional ','United States ','US ');
INSERT INTO airports VALUES('Alpine ','ALE','Alpine ','United States ','US ');
INSERT INTO airports VALUES('Alton ','ALN','Alton ','United States ','US ');
INSERT INTO airports VALUES('Altus ','LTS','Altus AFB ','United States ','US ');
INSERT INTO airports VALUES('Altus ','AXS','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Alyeska ','AQY','Alyeska ','United States ','US ');
INSERT INTO airports VALUES( 'Amarillo  ' ,'AMA','Rick Husband Amarillo International ','United States ','US ');
INSERT INTO airports VALUES('Amarillo ','TDW','Tradewind ','United States ','US ');
INSERT INTO airports VALUES('Ambler ','ABL','Ambler ','United States ','US ');
INSERT INTO airports VALUES('Amchitka ','AHT','Amchitka ','United States ','US ');
INSERT INTO airports VALUES('Amery ','AHH','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Ames ','AMW','Ames ','United States ','US ');
INSERT INTO airports VALUES('Amityville ','AYZ','Zahns ','United States ','US ');
INSERT INTO airports VALUES('Amook ','AOS','Amook ','United States ','US ');
INSERT INTO airports VALUES('Anacortes ','OTS','Anacortes ','United States ','US ');
INSERT INTO airports VALUES('Anacostia ','NDV','USN Heliport ','United States ','US ');
INSERT INTO airports VALUES('Anaheim ','ANA','Orange County Steel Salvage Heliport ','United States ','US ');
INSERT INTO airports VALUES('Anaktuvuk ','AKP','Anaktuvuk ','United States ','US ');
INSERT INTO airports VALUES('Anchorage ','EDF','Elmendorf Afb ','United States ','US ');
INSERT INTO airports VALUES('Anchorage ','ANC','Ted Stevens Anchorage International Airport ','United States ','US ');
INSERT INTO airports VALUES('Anchorage ','MRI','Merrill Field ','United States ','US ');
INSERT INTO airports VALUES('Anderson ','AID','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Anderson ','AND','Anderson ','United States ','US ');
INSERT INTO airports VALUES('Andrews ','ADR','Andrews ','United States ','US ');
INSERT INTO airports VALUES('Angel Fire ','AXX','Angel Fire ','United States ','US ');
INSERT INTO airports VALUES('Angola ','ANQ','Tri-State Steuben Cty ','United States ','US ');
INSERT INTO airports VALUES('Angoon ','AGN','Angoon ','United States ','US ');
INSERT INTO airports VALUES('Anguilla ','RFK','Rollang Field ','United States ','US ');
INSERT INTO airports VALUES('Aniak ','ANI','Aniak ','United States ','US ');
INSERT INTO airports VALUES('Anita Bay ','AIB','Anita Bay ','United States ','US ');
INSERT INTO airports VALUES( 'Ann Arbor MI ' ,'ARB','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Annapolis ','ANP','Lee ','United States ','US ');
INSERT INTO airports VALUES('Annette Island ','ANN','Annette Island ','United States ','US ');
INSERT INTO airports VALUES( 'Anniston AL ' ,'ANB','Anniston Metropolitan ','United States ','US ');
INSERT INTO airports VALUES('Anniston ','QAW','Ft Mcclellan Bus Trml ','United States ','US ');
INSERT INTO airports VALUES('Anniston ','RLI','Reilly AHP ','United States ','US ');
INSERT INTO airports VALUES('Anthony ','ANY','Anthony ','United States ','US ');
INSERT INTO airports VALUES('Antlers ','ATE','Antlers ','United States ','US ');
INSERT INTO airports VALUES('Anvik ','ANV','Anvik ','United States ','US ');
INSERT INTO airports VALUES('Apalachicola ','AAF','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Apple Valley ','APV','Apple Valley ','United States ','US ');
INSERT INTO airports VALUES('Appleton ','ATW','Outagamie County ','United States ','US ');
INSERT INTO airports VALUES('Arapahoe ','AHF','Municipal ','United States ','US ');
INSERT INTO airports VALUES('Arcata ','ACV','Arcata ','United States ','US ');
INSERT INTO airports VALUES('Arctic Village ','ARC','Arctic Village ','United States ','US ');
INSERT INTO airports VALUES('Ardmore ','AHD','Downtown ','United States ','US ');
INSERT INTO airports VALUES('Ardmore ','ADM','Ardmore Municipal Arpt ','United States ','US ');
INSERT INTO airports VALUES('Arlington Heights ','JLH','US Army Heliport ','United States ','US ');
INSERT INTO airports VALUES('Artesia ','ATS','Artesia ','United States ','US ');
INSERT INTO airports VALUES( 'Neptune ' ,'ARX','Asbury Park ','United States ','US ');
INSERT INTO airports VALUES('Ashland ','ASX','Ashland ','United States ','US ');
INSERT INTO airports VALUES('Ashley ','ASY','Ashley ','United States ','US ');
INSERT INTO airports VALUES('Aspen ','ASE','Aspen ','United States ','US ');
INSERT INTO airports VALUES('Astoria ','AST','Astoria ','United States ','US ');
INSERT INTO airports VALUES('Athens ','AHN','Athens ','United States ','US ');
INSERT INTO airports VALUES('Athens ','ATO','Ohio University ','United States ','US ');
INSERT INTO airports VALUES('Athens ','MMI','McMinn County ','United States ','US ');