-- ggchan
INSERT INTO carNames VALUES(1,'chevrolet','chevrolet chevelle malibu');
INSERT INTO carNames VALUES(2,'buick','buick skylark 320');
INSERT INTO carNames VALUES(3,'plymouth','plymouth satellite');
INSERT INTO carNames VALUES(4,'amc','amc rebel sst');
INSERT INTO carNames VALUES(5,'ford','ford torino');
INSERT INTO carNames VALUES(6,'ford','ford galaxie 500');
INSERT INTO carNames VALUES(7,'chevrolet','chevrolet impala');
INSERT INTO carNames VALUES(8,'plymouth','plymouth fury iii');
INSERT INTO carNames VALUES(9,'pontiac','pontiac catalina');
INSERT INTO carNames VALUES(10,'amc','amc ambassador dpl');
INSERT INTO carNames VALUES(11,'citroen','citroen ds-21 pallas');
INSERT INTO carNames VALUES(12,'chevrolet','chevrolet chevelle concours (sw)');
INSERT INTO carNames VALUES(13,'ford','ford torino (sw)');
INSERT INTO carNames VALUES(14,'plymouth','plymouth satellite (sw)');
INSERT INTO carNames VALUES(15,'amc','amc rebel sst (sw)');
INSERT INTO carNames VALUES(16,'dodge','dodge challenger se');
INSERT INTO carNames VALUES(17,'plymouth','plymouth cuda 340');
INSERT INTO carNames VALUES(18,'ford','ford mustang boss 302');
INSERT INTO carNames VALUES(19,'chevrolet','chevrolet monte carlo');
INSERT INTO carNames VALUES(20,'buick','buick estate wagon (sw)');
INSERT INTO carNames VALUES(21,'toyota','toyota corona mark ii');
INSERT INTO carNames VALUES(22,'plymouth','plymouth duster');
INSERT INTO carNames VALUES(23,'amc','amc hornet');
INSERT INTO carNames VALUES(24,'ford','ford maverick');
INSERT INTO carNames VALUES(25,'datsun','datsun pl510');
INSERT INTO carNames VALUES(26,'volkswagen','volkswagen 1131 deluxe sedan');
INSERT INTO carNames VALUES(27,'peugeot','peugeot 504');
INSERT INTO carNames VALUES(28,'audi','audi 100 ls');
INSERT INTO carNames VALUES(29,'saab','saab 99e');
INSERT INTO carNames VALUES(30,'bmw','bmw 2002');
INSERT INTO carNames VALUES(31,'amc','amc gremlin');
INSERT INTO carNames VALUES(32,'ford','ford f250');
INSERT INTO carNames VALUES(33,'chevrolet','chevy c20');
INSERT INTO carNames VALUES(34,'dodge','dodge d200');
INSERT INTO carNames VALUES(35,'hi','hi 1200d');
INSERT INTO carNames VALUES(36,'datsun','datsun pl510');
INSERT INTO carNames VALUES(37,'chevrolet','chevrolet vega 2300');
INSERT INTO carNames VALUES(38,'toyota','toyota corona');
INSERT INTO carNames VALUES(39,'ford','ford pinto');
INSERT INTO carNames VALUES(40,'volkswagen','volkswagen super beetle 117');
INSERT INTO carNames VALUES(41,'amc','amc gremlin');
INSERT INTO carNames VALUES(42,'plymouth','plymouth satellite custom');
INSERT INTO carNames VALUES(43,'chevrolet','chevrolet chevelle malibu');
INSERT INTO carNames VALUES(44,'ford','ford torino 500');
INSERT INTO carNames VALUES(45,'amc','amc matador');
INSERT INTO carNames VALUES(46,'chevrolet','chevrolet impala');
INSERT INTO carNames VALUES(47,'pontiac','pontiac catalina brougham');
INSERT INTO carNames VALUES(48,'ford','ford galaxie 500');
INSERT INTO carNames VALUES(49,'plymouth','plymouth fury iii');
INSERT INTO carNames VALUES(50,'dodge','dodge monaco (sw)');
INSERT INTO carNames VALUES(51,'ford','ford country squire (sw)');
INSERT INTO carNames VALUES(52,'pontiac','pontiac safari (sw)');
INSERT INTO carNames VALUES(53,'amc','amc hornet sportabout (sw)');
INSERT INTO carNames VALUES(54,'chevrolet','chevrolet vega (sw)');
INSERT INTO carNames VALUES(55,'pontiac','pontiac firebird');
INSERT INTO carNames VALUES(56,'ford','ford mustang');
INSERT INTO carNames VALUES(57,'mercury','mercury capri 2000');
INSERT INTO carNames VALUES(58,'opel','opel 1900');
INSERT INTO carNames VALUES(59,'peugeot','peugeot 304');
INSERT INTO carNames VALUES(60,'fiat','fiat 124b');
INSERT INTO carNames VALUES(61,'toyota','toyota corolla 1200');
INSERT INTO carNames VALUES(62,'datsun','datsun 1200');
INSERT INTO carNames VALUES(63,'volkswagen','volkswagen model 111');
INSERT INTO carNames VALUES(64,'plymouth','plymouth cricket');
INSERT INTO carNames VALUES(65,'toyota','toyota corona hardtop');
INSERT INTO carNames VALUES(66,'dodge','dodge colt hardtop');
INSERT INTO carNames VALUES(67,'volkswagen','volkswagen type 3');
INSERT INTO carNames VALUES(68,'chevrolet','chevrolet vega');
INSERT INTO carNames VALUES(69,'ford','ford pinto runabout');
INSERT INTO carNames VALUES(70,'chevrolet','chevrolet impala');
INSERT INTO carNames VALUES(71,'pontiac','pontiac catalina');
INSERT INTO carNames VALUES(72,'plymouth','plymouth fury iii');
INSERT INTO carNames VALUES(73,'ford','ford galaxie 500');
INSERT INTO carNames VALUES(74,'amc','amc ambassador sst');
INSERT INTO carNames VALUES(75,'mercury','mercury marquis');
INSERT INTO carNames VALUES(76,'buick','buick lesabre custom');
INSERT INTO carNames VALUES(77,'oldsmobile','oldsmobile delta 88 royale');
INSERT INTO carNames VALUES(78,'chrysler','chrysler newport royal');
INSERT INTO carNames VALUES(79,'mazda','mazda rx2 coupe');
INSERT INTO carNames VALUES(80,'amc','amc matador (sw)');
INSERT INTO carNames VALUES(81,'chevrolet','chevrolet chevelle concours (sw)');
INSERT INTO carNames VALUES(82,'ford','ford gran torino (sw)');
INSERT INTO carNames VALUES(83,'plymouth','plymouth satellite custom (sw)');
INSERT INTO carNames VALUES(84,'volvo','volvo 145e (sw)');
INSERT INTO carNames VALUES(85,'volkswagen','volkswagen 411 (sw)');
INSERT INTO carNames VALUES(86,'peugeot','peugeot 504 (sw)');
INSERT INTO carNames VALUES(87,'renault','renault 12 (sw)');
INSERT INTO carNames VALUES(88,'ford','ford pinto (sw)');
INSERT INTO carNames VALUES(89,'datsun','datsun 510 (sw)');
INSERT INTO carNames VALUES(90,'toyota','toyota corona mark ii (sw)');
INSERT INTO carNames VALUES(91,'dodge','dodge colt (sw)');
INSERT INTO carNames VALUES(92,'toyota','toyota corolla 1600 (sw)');
INSERT INTO carNames VALUES(93,'buick','buick century 350');
INSERT INTO carNames VALUES(94,'amc','amc matador');
INSERT INTO carNames VALUES(95,'chevrolet','chevrolet malibu');
INSERT INTO carNames VALUES(96,'ford','ford gran torino');
INSERT INTO carNames VALUES(97,'dodge','dodge coronet custom');
INSERT INTO carNames VALUES(98,'mercury','mercury marquis brougham');
INSERT INTO carNames VALUES(99,'chevrolet','chevrolet caprice classic');
INSERT INTO carNames VALUES(100,'ford','ford ltd');
INSERT INTO carNames VALUES(101,'plymouth','plymouth fury gran sedan');
INSERT INTO carNames VALUES(102,'chrysler','chrysler new yorker brougham');
INSERT INTO carNames VALUES(103,'buick','buick electra 225 custom');
INSERT INTO carNames VALUES(104,'amc','amc ambassador brougham');
INSERT INTO carNames VALUES(105,'plymouth','plymouth valiant');
INSERT INTO carNames VALUES(106,'chevrolet','chevrolet nova custom');
INSERT INTO carNames VALUES(107,'amc','amc hornet');
INSERT INTO carNames VALUES(108,'ford','ford maverick');
INSERT INTO carNames VALUES(109,'plymouth','plymouth duster');
INSERT INTO carNames VALUES(110,'volkswagen','volkswagen super beetle');
INSERT INTO carNames VALUES(111,'chevrolet','chevrolet impala');
INSERT INTO carNames VALUES(112,'ford','ford country');
INSERT INTO carNames VALUES(113,'plymouth','plymouth custom suburb');
INSERT INTO carNames VALUES(114,'oldsmobile','oldsmobile vista cruiser');
INSERT INTO carNames VALUES(115,'amc','amc gremlin');
INSERT INTO carNames VALUES(116,'toyota','toyota carina');
INSERT INTO carNames VALUES(117,'chevrolet','chevrolet vega');
INSERT INTO carNames VALUES(118,'datsun','datsun 610');
INSERT INTO carNames VALUES(119,'mazda','mazda rx3');
INSERT INTO carNames VALUES(120,'ford','ford pinto');
INSERT INTO carNames VALUES(121,'mercury','mercury capri v6');
INSERT INTO carNames VALUES(122,'fiat','fiat 124 sport coupe');
INSERT INTO carNames VALUES(123,'chevrolet','chevrolet monte carlo s');
INSERT INTO carNames VALUES(124,'pontiac','pontiac grand prix');
INSERT INTO carNames VALUES(125,'fiat','fiat 128');
INSERT INTO carNames VALUES(126,'opel','opel manta');
INSERT INTO carNames VALUES(127,'audi','audi 100ls');
INSERT INTO carNames VALUES(128,'volvo','volvo 144ea');
INSERT INTO carNames VALUES(129,'dodge','dodge dart custom');
INSERT INTO carNames VALUES(130,'saab','saab 99le');
INSERT INTO carNames VALUES(131,'toyota','toyota mark ii');
INSERT INTO carNames VALUES(132,'oldsmobile','oldsmobile omega');
INSERT INTO carNames VALUES(133,'plymouth','plymouth duster');
INSERT INTO carNames VALUES(134,'ford','ford maverick');
INSERT INTO carNames VALUES(135,'amc','amc hornet');
INSERT INTO carNames VALUES(136,'chevrolet','chevrolet nova');
INSERT INTO carNames VALUES(137,'datsun','datsun b210');
INSERT INTO carNames VALUES(138,'ford','ford pinto');
INSERT INTO carNames VALUES(139,'toyota','toyota corolla 1200');
INSERT INTO carNames VALUES(140,'chevrolet','chevrolet vega');
INSERT INTO carNames VALUES(141,'chevrolet','chevrolet chevelle malibu classic');
INSERT INTO carNames VALUES(142,'amc','amc matador');
INSERT INTO carNames VALUES(143,'plymouth','plymouth satellite sebring');
INSERT INTO carNames VALUES(144,'ford','ford gran torino');
INSERT INTO carNames VALUES(145,'buick','buick century luxus (sw)');
INSERT INTO carNames VALUES(146,'dodge','dodge coronet custom (sw)');
INSERT INTO carNames VALUES(147,'ford','ford gran torino (sw)');
INSERT INTO carNames VALUES(148,'amc','amc matador (sw)');
INSERT INTO carNames VALUES(149,'audi','audi fox');
INSERT INTO carNames VALUES(150,'volkswagen','volkswagen dasher');
INSERT INTO carNames VALUES(151,'opel','opel manta');
INSERT INTO carNames VALUES(152,'toyota','toyota corona');
INSERT INTO carNames VALUES(153,'datsun','datsun 710');
INSERT INTO carNames VALUES(154,'dodge','dodge colt');
INSERT INTO carNames VALUES(155,'fiat','fiat 128');
INSERT INTO carNames VALUES(156,'fiat','fiat 124 tc');
INSERT INTO carNames VALUES(157,'honda','honda civic');
INSERT INTO carNames VALUES(158,'subaru','subaru');
INSERT INTO carNames VALUES(159,'fiat','fiat x1.9');
INSERT INTO carNames VALUES(160,'plymouth','plymouth valiant custom');
INSERT INTO carNames VALUES(161,'chevrolet','chevrolet nova');
INSERT INTO carNames VALUES(162,'mercury','mercury monarch');
INSERT INTO carNames VALUES(163,'ford','ford maverick');
INSERT INTO carNames VALUES(164,'pontiac','pontiac catalina');
INSERT INTO carNames VALUES(165,'chevrolet','chevrolet bel air');
INSERT INTO carNames VALUES(166,'plymouth','plymouth grand fury');
INSERT INTO carNames VALUES(167,'ford','ford ltd');
INSERT INTO carNames VALUES(168,'buick','buick century');
INSERT INTO carNames VALUES(169,'chevrolet','chevrolet chevelle malibu');
INSERT INTO carNames VALUES(170,'amc','amc matador');
INSERT INTO carNames VALUES(171,'plymouth','plymouth fury');
INSERT INTO carNames VALUES(172,'buick','buick skyhawk');
INSERT INTO carNames VALUES(173,'chevrolet','chevrolet monza 2+2');
INSERT INTO carNames VALUES(174,'ford','ford mustang ii');
INSERT INTO carNames VALUES(175,'toyota','toyota corolla');
INSERT INTO carNames VALUES(176,'ford','ford pinto');
INSERT INTO carNames VALUES(177,'amc','amc gremlin');
INSERT INTO carNames VALUES(178,'pontiac','pontiac astro');
INSERT INTO carNames VALUES(179,'toyota','toyota corona');
INSERT INTO carNames VALUES(180,'volkswagen','volkswagen dasher');
INSERT INTO carNames VALUES(181,'datsun','datsun 710');
INSERT INTO carNames VALUES(182,'ford','ford pinto');
INSERT INTO carNames VALUES(183,'volkswagen','volkswagen rabbit');
INSERT INTO carNames VALUES(184,'amc','amc pacer');
INSERT INTO carNames VALUES(185,'audi','audi 100ls');
INSERT INTO carNames VALUES(186,'peugeot','peugeot 504');
INSERT INTO carNames VALUES(187,'volvo','volvo 244dl');
INSERT INTO carNames VALUES(188,'saab','saab 99le');
INSERT INTO carNames VALUES(189,'honda','honda civic cvcc');
INSERT INTO carNames VALUES(190,'fiat','fiat 131');
INSERT INTO carNames VALUES(191,'opel','opel 1900');
INSERT INTO carNames VALUES(192,'capri','capri ii');
INSERT INTO carNames VALUES(193,'dodge','dodge colt');
INSERT INTO carNames VALUES(194,'renault','renault 12tl');
INSERT INTO carNames VALUES(195,'chevrolet','chevrolet chevelle malibu classic');
INSERT INTO carNames VALUES(196,'dodge','dodge coronet brougham');
INSERT INTO carNames VALUES(197,'amc','amc matador');
INSERT INTO carNames VALUES(198,'ford','ford gran torino');
INSERT INTO carNames VALUES(199,'plymouth','plymouth valiant');
INSERT INTO carNames VALUES(200,'chevrolet','chevrolet nova');
INSERT INTO carNames VALUES(201,'ford','ford maverick');
INSERT INTO carNames VALUES(202,'amc','amc hornet');
INSERT INTO carNames VALUES(203,'chevrolet','chevrolet chevette');
INSERT INTO carNames VALUES(204,'chevrolet','chevrolet woody');
INSERT INTO carNames VALUES(205,'volkswagen','vw rabbit');
INSERT INTO carNames VALUES(206,'honda','honda civic');
INSERT INTO carNames VALUES(207,'dodge','dodge aspen se');
INSERT INTO carNames VALUES(208,'ford','ford granada ghia');
INSERT INTO carNames VALUES(209,'pontiac','pontiac ventura sj');
INSERT INTO carNames VALUES(210,'amc','amc pacer d/l');
INSERT INTO carNames VALUES(211,'volkswagen','volkswagen rabbit');
INSERT INTO carNames VALUES(212,'datsun','datsun b-210');
INSERT INTO carNames VALUES(213,'toyota','toyota corolla');
INSERT INTO carNames VALUES(214,'ford','ford pinto');
INSERT INTO carNames VALUES(215,'volvo','volvo 245');
INSERT INTO carNames VALUES(216,'plymouth','plymouth volare premier v8');
INSERT INTO carNames VALUES(217,'peugeot','peugeot 504');
INSERT INTO carNames VALUES(218,'toyota','toyota mark ii');
INSERT INTO carNames VALUES(219,'mercedes-benz','mercedes-benz 280s');
INSERT INTO carNames VALUES(220,'cadillac','cadillac seville');
INSERT INTO carNames VALUES(221,'chevrolet','chevy c10');
INSERT INTO carNames VALUES(222,'ford','ford f108');
INSERT INTO carNames VALUES(223,'dodge','dodge d100');
INSERT INTO carNames VALUES(224,'honda','honda accord cvcc');
INSERT INTO carNames VALUES(225,'buick','buick opel isuzu deluxe');
INSERT INTO carNames VALUES(226,'renault','renault 5 gtl');
INSERT INTO carNames VALUES(227,'plymouth','plymouth arrow gs');
INSERT INTO carNames VALUES(228,'datsun','datsun f-10 hatchback');
INSERT INTO carNames VALUES(229,'chevrolet','chevrolet caprice classic');
INSERT INTO carNames VALUES(230,'oldsmobile','oldsmobile cutlass supreme');
INSERT INTO carNames VALUES(231,'dodge','dodge monaco brougham');
INSERT INTO carNames VALUES(232,'mercury','mercury cougar brougham');
INSERT INTO carNames VALUES(233,'chevrolet','chevrolet concours');
INSERT INTO carNames VALUES(234,'buick','buick skylark');
INSERT INTO carNames VALUES(235,'plymouth','plymouth volare custom');
INSERT INTO carNames VALUES(236,'ford','ford granada');
INSERT INTO carNames VALUES(237,'pontiac','pontiac grand prix lj');
INSERT INTO carNames VALUES(238,'chevrolet','chevrolet monte carlo landau');
INSERT INTO carNames VALUES(239,'chrysler','chrysler cordoba');
INSERT INTO carNames VALUES(240,'ford','ford thunderbird');
INSERT INTO carNames VALUES(241,'volkswagen','volkswagen rabbit custom');
INSERT INTO carNames VALUES(242,'pontiac','pontiac sunbird coupe');
INSERT INTO carNames VALUES(243,'toyota','toyota corolla liftback');
INSERT INTO carNames VALUES(244,'ford','ford mustang ii 2+2');
INSERT INTO carNames VALUES(245,'chevrolet','chevrolet chevette');
INSERT INTO carNames VALUES(246,'dodge','dodge colt m/m');
INSERT INTO carNames VALUES(247,'subaru','subaru dl');
INSERT INTO carNames VALUES(248,'volkswagen','volkswagen dasher');
INSERT INTO carNames VALUES(249,'datsun','datsun 810');
INSERT INTO carNames VALUES(250,'bmw','bmw 320i');
INSERT INTO carNames VALUES(251,'mazda','mazda rx-4');
INSERT INTO carNames VALUES(252,'volkswagen','volkswagen rabbit custom diesel');
INSERT INTO carNames VALUES(253,'ford','ford fiesta');
INSERT INTO carNames VALUES(254,'mazda','mazda glc deluxe');
INSERT INTO carNames VALUES(255,'datsun','datsun b210 gx');
INSERT INTO carNames VALUES(256,'honda','honda civic cvcc');
INSERT INTO carNames VALUES(257,'oldsmobile','oldsmobile cutlass salon brougham');
INSERT INTO carNames VALUES(258,'dodge','dodge diplomat');
INSERT INTO carNames VALUES(259,'mercury','mercury monarch ghia');
INSERT INTO carNames VALUES(260,'pontiac','pontiac phoenix lj');
INSERT INTO carNames VALUES(261,'chevrolet','chevrolet malibu');
INSERT INTO carNames VALUES(262,'ford','ford fairmont (auto)');
INSERT INTO carNames VALUES(263,'ford','ford fairmont (man)');
INSERT INTO carNames VALUES(264,'plymouth','plymouth volare');
INSERT INTO carNames VALUES(265,'amc','amc concord');
INSERT INTO carNames VALUES(266,'buick','buick century special');
INSERT INTO carNames VALUES(267,'mercury','mercury zephyr');
INSERT INTO carNames VALUES(268,'dodge','dodge aspen');
INSERT INTO carNames VALUES(269,'amc','amc concord d/l');
INSERT INTO carNames VALUES(270,'chevrolet','chevrolet monte carlo landau');
INSERT INTO carNames VALUES(271,'buick','buick regal sport coupe (turbo)');
INSERT INTO carNames VALUES(272,'ford','ford futura');
INSERT INTO carNames VALUES(273,'dodge','dodge magnum xe');
INSERT INTO carNames VALUES(274,'chevrolet','chevrolet chevette');
INSERT INTO carNames VALUES(275,'toyota','toyota corona');
INSERT INTO carNames VALUES(276,'datsun','datsun 510');
INSERT INTO carNames VALUES(277,'dodge','dodge omni');
INSERT INTO carNames VALUES(278,'toyota','toyota celica gt liftback');
INSERT INTO carNames VALUES(279,'plymouth','plymouth sapporo');
INSERT INTO carNames VALUES(280,'oldsmobile','oldsmobile starfire sx');
INSERT INTO carNames VALUES(281,'datsun','datsun 200-sx');
INSERT INTO carNames VALUES(282,'audi','audi 5000');
INSERT INTO carNames VALUES(283,'volvo','volvo 264gl');
INSERT INTO carNames VALUES(284,'saab','saab 99gle');
INSERT INTO carNames VALUES(285,'peugeot','peugeot 604sl');
INSERT INTO carNames VALUES(286,'volkswagen','volkswagen scirocco');
INSERT INTO carNames VALUES(287,'honda','honda accord lx');
INSERT INTO carNames VALUES(288,'pontiac','pontiac lemans v6');
INSERT INTO carNames VALUES(289,'mercury','mercury zephyr 6');
INSERT INTO carNames VALUES(290,'ford','ford fairmont 4');
INSERT INTO carNames VALUES(291,'amc','amc concord dl 6');
INSERT INTO carNames VALUES(292,'dodge','dodge aspen 6');
INSERT INTO carNames VALUES(293,'chevrolet','chevrolet caprice classic');
INSERT INTO carNames VALUES(294,'ford','ford ltd landau');
INSERT INTO carNames VALUES(295,'mercury','mercury grand marquis');
INSERT INTO carNames VALUES(296,'dodge','dodge st. regis');
INSERT INTO carNames VALUES(297,'buick','buick estate wagon (sw)');
INSERT INTO carNames VALUES(298,'ford','ford country squire (sw)');
INSERT INTO carNames VALUES(299,'chevrolet','chevrolet malibu classic (sw)');
INSERT INTO carNames VALUES(300,'chrysler','chrysler lebaron town @ country (sw)');
INSERT INTO carNames VALUES(301,'volkswagen','vw rabbit custom');
INSERT INTO carNames VALUES(302,'mazda', 'mazda glc deluxe');
INSERT INTO carNames VALUES(303,'dodge','dodge colt hatchback custom');
INSERT INTO carNames VALUES(304,'amc','amc spirit dl');
INSERT INTO carNames VALUES(305,'mercedes','mercedes benz 300d');
INSERT INTO carNames VALUES(306,'cadillac','cadillac eldorado');
INSERT INTO carNames VALUES(307,'peugeot','peugeot 504');
INSERT INTO carNames VALUES(308,'oldsmobile','oldsmobile cutlass salon brougham');
INSERT INTO carNames VALUES(309,'plymouth','plymouth horizon');
INSERT INTO carNames VALUES(310,'plymouth','plymouth horizon tc3');
INSERT INTO carNames VALUES(311,'datsun','datsun 210');
INSERT INTO carNames VALUES(312,'fiat','fiat strada custom');
INSERT INTO carNames VALUES(313,'buick','buick skylark limited');
INSERT INTO carNames VALUES(314,'chevrolet','chevrolet citation');
INSERT INTO carNames VALUES(315,'oldsmobile','oldsmobile omega brougham');
INSERT INTO carNames VALUES(316,'pontiac','pontiac phoenix');
INSERT INTO carNames VALUES(317,'volkswagen','vw rabbit');
INSERT INTO carNames VALUES(318,'toyota','toyota corolla tercel');
INSERT INTO carNames VALUES(319,'chevrolet','chevrolet chevette');
INSERT INTO carNames VALUES(320,'datsun','datsun 310');
INSERT INTO carNames VALUES(321,'chevrolet','chevrolet citation');
INSERT INTO carNames VALUES(322,'ford','ford fairmont');
INSERT INTO carNames VALUES(323,'amc','amc concord');
INSERT INTO carNames VALUES(324,'dodge','dodge aspen');
INSERT INTO carNames VALUES(325,'audi','audi 4000');
INSERT INTO carNames VALUES(326,'toyota','toyota corona liftback');
INSERT INTO carNames VALUES(327,'mazda','mazda 626');
INSERT INTO carNames VALUES(328,'datsun','datsun 510 hatchback');
INSERT INTO carNames VALUES(329,'toyota','toyota corolla');
INSERT INTO carNames VALUES(330,'mazda','mazda glc');
INSERT INTO carNames VALUES(331,'dodge','dodge colt');
INSERT INTO carNames VALUES(332,'datsun','datsun 210');
INSERT INTO carNames VALUES(333,'volkswagen','vw rabbit c (diesel)');
INSERT INTO carNames VALUES(334,'volkswagen','vw dasher (diesel)');
INSERT INTO carNames VALUES(335,'audi','audi 5000s (diesel)');
INSERT INTO carNames VALUES(336,'mercedes-benz','mercedes-benz 240d');
INSERT INTO carNames VALUES(337,'honda','honda civic 1500 gl');
INSERT INTO carNames VALUES(338,'renault','renault lecar deluxe');
INSERT INTO carNames VALUES(339,'subaru','subaru dl');
INSERT INTO carNames VALUES(340, 'volkswagen','volkswagen rabbit');
INSERT INTO carNames VALUES(341,'datsun','datsun 280-zx');
INSERT INTO carNames VALUES(342,'mazda','mazda rx-7 gs');
INSERT INTO carNames VALUES(343,'triumph','triumph tr7 coupe');
INSERT INTO carNames VALUES(344,'ford','ford mustang cobra');
INSERT INTO carNames VALUES(345,'honda','honda accord');
INSERT INTO carNames VALUES(346,'plymouth','plymouth reliant');
INSERT INTO carNames VALUES(347,'buick','buick skylark');
INSERT INTO carNames VALUES(348,'dodge','dodge aries wagon (sw)');
INSERT INTO carNames VALUES(349,'chevrolet','chevrolet citation');
INSERT INTO carNames VALUES(350,'plymouth','plymouth reliant');
INSERT INTO carNames VALUES(351,'toyota','toyota starlet');
INSERT INTO carNames VALUES(352,'plymouth','plymouth champ');
INSERT INTO carNames VALUES(353,'honda','honda civic 1300');
INSERT INTO carNames VALUES(354,'subaru','subaru');
INSERT INTO carNames VALUES(355,'datsun','datsun 210 mpg');
INSERT INTO carNames VALUES(356,'toyota','toyota tercel');
INSERT INTO carNames VALUES(357,'mazda','mazda glc 4');
INSERT INTO carNames VALUES(358,'plymouth','plymouth horizon 4');
INSERT INTO carNames VALUES(359,'ford','ford escort 4w');
INSERT INTO carNames VALUES(360,'ford','ford escort 2h');
INSERT INTO carNames VALUES(361,'volkswagen','volkswagen jetta');
INSERT INTO carNames VALUES(362,'renault','renault 18i');
INSERT INTO carNames VALUES(363,'honda','honda prelude');
INSERT INTO carNames VALUES(364,'toyota','toyota corolla');
INSERT INTO carNames VALUES(365,'datsun','datsun 200sx');
INSERT INTO carNames VALUES(366,'mazda','mazda 626');
INSERT INTO carNames VALUES(367,'peugeot','peugeot 505s turbo diesel');
INSERT INTO carNames VALUES(368,'saab','saab 900s');
INSERT INTO carNames VALUES(369,'volvo','volvo diesel');
INSERT INTO carNames VALUES(370,'toyota','toyota cressida');
INSERT INTO carNames VALUES(371,'datsun','datsun 810 maxima');
INSERT INTO carNames VALUES(372,'buick','buick century');
INSERT INTO carNames VALUES(373,'oldsmobile','oldsmobile cutlass ls');
INSERT INTO carNames VALUES(374,'ford','ford granada gl');
INSERT INTO carNames VALUES(375,'chrysler','chrysler lebaron salon');
INSERT INTO carNames VALUES(376,'chevrolet','chevrolet cavalier');
INSERT INTO carNames VALUES(377,'chevrolet','chevrolet cavalier wagon');
INSERT INTO carNames VALUES(378,'chevrolet','chevrolet cavalier 2-door');
INSERT INTO carNames VALUES(379,'pontiac','pontiac j2000 se hatchback');
INSERT INTO carNames VALUES(380,'dodge','dodge aries se');
INSERT INTO carNames VALUES(381,'pontiac','pontiac phoenix');
INSERT INTO carNames VALUES(382,'ford','ford fairmont futura');
INSERT INTO carNames VALUES(383,'amc','amc concord dl');
INSERT INTO carNames VALUES(384,'volkswagen','volkswagen rabbit l');
INSERT INTO carNames VALUES(385,'mazda','mazda glc custom l');
INSERT INTO carNames VALUES(386,'mazda','mazda glc custom');
INSERT INTO carNames VALUES(387,'plymouth','plymouth horizon miser');
INSERT INTO carNames VALUES(388,'mercury','mercury lynx l');
INSERT INTO carNames VALUES(389,'nissan','nissan stanza xe');
INSERT INTO carNames VALUES(390,'honda','honda accord');
INSERT INTO carNames VALUES(391,'toyota','toyota corolla');
INSERT INTO carNames VALUES(392,'honda','honda civic');
INSERT INTO carNames VALUES(393,'honda','honda civic (auto)');
INSERT INTO carNames VALUES(394,'datsun','datsun 310 gx');
INSERT INTO carNames VALUES(395,'buick','buick century limited');
INSERT INTO carNames VALUES(396,'oldsmobile','oldsmobile cutlass ciera (diesel)');
INSERT INTO carNames VALUES(397,'chrysler','chrysler lebaron medallion');
INSERT INTO carNames VALUES(398,'ford','ford granada l');
INSERT INTO carNames VALUES(399,'toyota','toyota celica gt');
INSERT INTO carNames VALUES(400,'dodge','dodge charger 2.2');
INSERT INTO carNames VALUES(401,'chevrolet','chevrolet camaro');
INSERT INTO carNames VALUES(402,'ford','ford mustang gl');
INSERT INTO carNames VALUES(403,'volkswagen','vw pickup');
INSERT INTO carNames VALUES(404,'dodge','dodge rampage');
INSERT INTO carNames VALUES(405,'ford','ford ranger');
INSERT INTO carNames VALUES(406,'chevrolet','chevy s-10');